//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.UchetMedZueva7
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Класс вред фактор.
    /// </summary>
    // *** Start programmer edit section *** (КлассВредФактор CustomAttributes)

    // *** End programmer edit section *** (КлассВредФактор CustomAttributes)
    [AutoAltered()]
    [Caption("Класс вред фактор")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("КлассВредФакторE", new string[] {
            "Номер as \'Номер\'",
            "Наименование as \'Наименование\'"})]
    [View("КлассВредФакторL", new string[] {
            "Номер as \'Номер\'",
            "Наименование as \'Наименование\'"})]
    public class КлассВредФактор : ICSSoft.STORMNET.DataObject
    {
        
        private int fНомер;
        
        private string fНаименование;
        
        // *** Start programmer edit section *** (КлассВредФактор CustomMembers)

        // *** End programmer edit section *** (КлассВредФактор CustomMembers)

        
        /// <summary>
        /// Наименование.
        /// </summary>
        // *** Start programmer edit section *** (КлассВредФактор.Наименование CustomAttributes)

        // *** End programmer edit section *** (КлассВредФактор.Наименование CustomAttributes)
        [StrLen(255)]
        public virtual string Наименование
        {
            get
            {
                // *** Start programmer edit section *** (КлассВредФактор.Наименование Get start)

                // *** End programmer edit section *** (КлассВредФактор.Наименование Get start)
                string result = this.fНаименование;
                // *** Start programmer edit section *** (КлассВредФактор.Наименование Get end)

                // *** End programmer edit section *** (КлассВредФактор.Наименование Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (КлассВредФактор.Наименование Set start)

                // *** End programmer edit section *** (КлассВредФактор.Наименование Set start)
                this.fНаименование = value;
                // *** Start programmer edit section *** (КлассВредФактор.Наименование Set end)

                // *** End programmer edit section *** (КлассВредФактор.Наименование Set end)
            }
        }
        
        /// <summary>
        /// Номер.
        /// </summary>
        // *** Start programmer edit section *** (КлассВредФактор.Номер CustomAttributes)

        // *** End programmer edit section *** (КлассВредФактор.Номер CustomAttributes)
        public virtual int Номер
        {
            get
            {
                // *** Start programmer edit section *** (КлассВредФактор.Номер Get start)

                // *** End programmer edit section *** (КлассВредФактор.Номер Get start)
                int result = this.fНомер;
                // *** Start programmer edit section *** (КлассВредФактор.Номер Get end)

                // *** End programmer edit section *** (КлассВредФактор.Номер Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (КлассВредФактор.Номер Set start)

                // *** End programmer edit section *** (КлассВредФактор.Номер Set start)
                this.fНомер = value;
                // *** Start programmer edit section *** (КлассВредФактор.Номер Set end)

                // *** End programmer edit section *** (КлассВредФактор.Номер Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "КлассВредФакторE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КлассВредФакторE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КлассВредФакторE", typeof(IIS.UchetMedZueva7.КлассВредФактор));
                }
            }
            
            /// <summary>
            /// "КлассВредФакторL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КлассВредФакторL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КлассВредФакторL", typeof(IIS.UchetMedZueva7.КлассВредФактор));
                }
            }
        }
    }
}
