//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.UchetMedZueva7
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Организации.
    /// </summary>
    // *** Start programmer edit section *** (Организации CustomAttributes)

    // *** End programmer edit section *** (Организации CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ОрганизацииE", new string[] {
            "Наименование as \'Наименование\'",
            "ИНН as \'ИНН\'",
            "КПП as \'КПП\'",
            "ОГРН as \'ОГРН\'",
            "Телефон as \'Телефон\'",
            "Почта as \'Почта\'",
            "ЮрАдрес as \'Юр адрес\'"})]
    [View("ОрганизацииL", new string[] {
            "Наименование as \'Наименование\'",
            "ИНН as \'ИНН\'",
            "КПП as \'КПП\'",
            "ОГРН as \'ОГРН\'",
            "Телефон as \'Телефон\'",
            "Почта as \'Почта\'",
            "ЮрАдрес as \'Юр адрес\'"})]
    public class Организации : ICSSoft.STORMNET.DataObject
    {
        
        private string fНаименование;
        
        private int fИНН;
        
        private int fКПП;
        
        private int fОГРН;
        
        private int fТелефон;
        
        private string fПочта;
        
        private string fЮрАдрес;
        
        // *** Start programmer edit section *** (Организации CustomMembers)

        // *** End programmer edit section *** (Организации CustomMembers)

        
        /// <summary>
        /// ИНН.
        /// </summary>
        // *** Start programmer edit section *** (Организации.ИНН CustomAttributes)

        // *** End programmer edit section *** (Организации.ИНН CustomAttributes)
        public virtual int ИНН
        {
            get
            {
                // *** Start programmer edit section *** (Организации.ИНН Get start)

                // *** End programmer edit section *** (Организации.ИНН Get start)
                int result = this.fИНН;
                // *** Start programmer edit section *** (Организации.ИНН Get end)

                // *** End programmer edit section *** (Организации.ИНН Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Организации.ИНН Set start)

                // *** End programmer edit section *** (Организации.ИНН Set start)
                this.fИНН = value;
                // *** Start programmer edit section *** (Организации.ИНН Set end)

                // *** End programmer edit section *** (Организации.ИНН Set end)
            }
        }
        
        /// <summary>
        /// КПП.
        /// </summary>
        // *** Start programmer edit section *** (Организации.КПП CustomAttributes)

        // *** End programmer edit section *** (Организации.КПП CustomAttributes)
        public virtual int КПП
        {
            get
            {
                // *** Start programmer edit section *** (Организации.КПП Get start)

                // *** End programmer edit section *** (Организации.КПП Get start)
                int result = this.fКПП;
                // *** Start programmer edit section *** (Организации.КПП Get end)

                // *** End programmer edit section *** (Организации.КПП Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Организации.КПП Set start)

                // *** End programmer edit section *** (Организации.КПП Set start)
                this.fКПП = value;
                // *** Start programmer edit section *** (Организации.КПП Set end)

                // *** End programmer edit section *** (Организации.КПП Set end)
            }
        }
        
        /// <summary>
        /// Наименование.
        /// </summary>
        // *** Start programmer edit section *** (Организации.Наименование CustomAttributes)

        // *** End programmer edit section *** (Организации.Наименование CustomAttributes)
        [StrLen(255)]
        public virtual string Наименование
        {
            get
            {
                // *** Start programmer edit section *** (Организации.Наименование Get start)

                // *** End programmer edit section *** (Организации.Наименование Get start)
                string result = this.fНаименование;
                // *** Start programmer edit section *** (Организации.Наименование Get end)

                // *** End programmer edit section *** (Организации.Наименование Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Организации.Наименование Set start)

                // *** End programmer edit section *** (Организации.Наименование Set start)
                this.fНаименование = value;
                // *** Start programmer edit section *** (Организации.Наименование Set end)

                // *** End programmer edit section *** (Организации.Наименование Set end)
            }
        }
        
        /// <summary>
        /// ОГРН.
        /// </summary>
        // *** Start programmer edit section *** (Организации.ОГРН CustomAttributes)

        // *** End programmer edit section *** (Организации.ОГРН CustomAttributes)
        public virtual int ОГРН
        {
            get
            {
                // *** Start programmer edit section *** (Организации.ОГРН Get start)

                // *** End programmer edit section *** (Организации.ОГРН Get start)
                int result = this.fОГРН;
                // *** Start programmer edit section *** (Организации.ОГРН Get end)

                // *** End programmer edit section *** (Организации.ОГРН Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Организации.ОГРН Set start)

                // *** End programmer edit section *** (Организации.ОГРН Set start)
                this.fОГРН = value;
                // *** Start programmer edit section *** (Организации.ОГРН Set end)

                // *** End programmer edit section *** (Организации.ОГРН Set end)
            }
        }
        
        /// <summary>
        /// Почта.
        /// </summary>
        // *** Start programmer edit section *** (Организации.Почта CustomAttributes)

        // *** End programmer edit section *** (Организации.Почта CustomAttributes)
        [StrLen(255)]
        public virtual string Почта
        {
            get
            {
                // *** Start programmer edit section *** (Организации.Почта Get start)

                // *** End programmer edit section *** (Организации.Почта Get start)
                string result = this.fПочта;
                // *** Start programmer edit section *** (Организации.Почта Get end)

                // *** End programmer edit section *** (Организации.Почта Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Организации.Почта Set start)

                // *** End programmer edit section *** (Организации.Почта Set start)
                this.fПочта = value;
                // *** Start programmer edit section *** (Организации.Почта Set end)

                // *** End programmer edit section *** (Организации.Почта Set end)
            }
        }
        
        /// <summary>
        /// Телефон.
        /// </summary>
        // *** Start programmer edit section *** (Организации.Телефон CustomAttributes)

        // *** End programmer edit section *** (Организации.Телефон CustomAttributes)
        public virtual int Телефон
        {
            get
            {
                // *** Start programmer edit section *** (Организации.Телефон Get start)

                // *** End programmer edit section *** (Организации.Телефон Get start)
                int result = this.fТелефон;
                // *** Start programmer edit section *** (Организации.Телефон Get end)

                // *** End programmer edit section *** (Организации.Телефон Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Организации.Телефон Set start)

                // *** End programmer edit section *** (Организации.Телефон Set start)
                this.fТелефон = value;
                // *** Start programmer edit section *** (Организации.Телефон Set end)

                // *** End programmer edit section *** (Организации.Телефон Set end)
            }
        }
        
        /// <summary>
        /// ЮрАдрес.
        /// </summary>
        // *** Start programmer edit section *** (Организации.ЮрАдрес CustomAttributes)

        // *** End programmer edit section *** (Организации.ЮрАдрес CustomAttributes)
        [StrLen(255)]
        public virtual string ЮрАдрес
        {
            get
            {
                // *** Start programmer edit section *** (Организации.ЮрАдрес Get start)

                // *** End programmer edit section *** (Организации.ЮрАдрес Get start)
                string result = this.fЮрАдрес;
                // *** Start programmer edit section *** (Организации.ЮрАдрес Get end)

                // *** End programmer edit section *** (Организации.ЮрАдрес Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Организации.ЮрАдрес Set start)

                // *** End programmer edit section *** (Организации.ЮрАдрес Set start)
                this.fЮрАдрес = value;
                // *** Start programmer edit section *** (Организации.ЮрАдрес Set end)

                // *** End programmer edit section *** (Организации.ЮрАдрес Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ОрганизацииE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОрганизацииE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОрганизацииE", typeof(IIS.UchetMedZueva7.Организации));
                }
            }
            
            /// <summary>
            /// "ОрганизацииL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОрганизацииL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОрганизацииL", typeof(IIS.UchetMedZueva7.Организации));
                }
            }
        }
    }
}
