//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.UchetMedZueva7
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Период мед.
    /// </summary>
    // *** Start programmer edit section *** (ПериодМед CustomAttributes)

    // *** End programmer edit section *** (ПериодМед CustomAttributes)
    public enum ПериодМед
    {
        
        // *** Start programmer edit section *** (ПериодМед.РазВГод CustomAttributes)

        // *** End programmer edit section *** (ПериодМед.РазВГод CustomAttributes)
        [Caption("РазВГод")]
        РазВГод,
        
        // *** Start programmer edit section *** (ПериодМед.РазВДваГода CustomAttributes)

        // *** End programmer edit section *** (ПериодМед.РазВДваГода CustomAttributes)
        [Caption("РазВДваГода")]
        РазВДваГода,
    }
}
