//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.UchetMedZueva7
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Период мед.
    /// </summary>
    // *** Start programmer edit section *** (ПериодМед CustomAttributes)

    // *** End programmer edit section *** (ПериодМед CustomAttributes)
    public enum ПериодМед
    {
        
        // *** Start programmer edit section *** (ПериодМед.1разВГод CustomAttributes)

        // *** End programmer edit section *** (ПериодМед.1разВГод CustomAttributes)
        [Caption("1разВГод")]
        1разВГод,
        
        // *** Start programmer edit section *** (ПериодМед.1разВ2Года CustomAttributes)

        // *** End programmer edit section *** (ПериодМед.1разВ2Года CustomAttributes)
        [Caption("1разВ2Года")]
        1разВ2Года,
    }
}
