//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.UchetMedZueva7
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Подразделения.
    /// </summary>
    // *** Start programmer edit section *** (Подразделения CustomAttributes)

    // *** End programmer edit section *** (Подразделения CustomAttributes)
    public enum Подразделения
    {
        
        // *** Start programmer edit section *** (Подразделения.ОтделТехБез CustomAttributes)

        // *** End programmer edit section *** (Подразделения.ОтделТехБез CustomAttributes)
        [Caption("ОтделТехБез")]
        ОтделТехБез,
        
        // *** Start programmer edit section *** (Подразделения.ОтделОхрТруда CustomAttributes)

        // *** End programmer edit section *** (Подразделения.ОтделОхрТруда CustomAttributes)
        [Caption("ОтделОхрТруда")]
        ОтделОхрТруда,
        
        // *** Start programmer edit section *** (Подразделения.ТранспортОтдел CustomAttributes)

        // *** End programmer edit section *** (Подразделения.ТранспортОтдел CustomAttributes)
        [Caption("ТранспортОтдел")]
        ТранспортОтдел,
    }
}
